import { FileStorage, Megaphone, Flights } from '../assets/icons';
export const dummyTransactions = [
  {
    id: 1,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '+ S$ 150',
    amountColor: 'green',
    type: 'Refund on debit card',
    icon: FileStorage,
  },
  {
    id: 2,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '- S$ 150',
    amountColor: 'black',
    type: 'Charged to debit card',
    icon: Megaphone,
  },
  {
    id: 3,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '- S$ 150',
    amountColor: 'black',
    type: 'Charged to debit card',
    icon: Flights,
  },
  {
    id: 4,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '- S$ 150',
    amountColor: 'black',
    type: 'Charged to debit card',
    icon: FileStorage,
  },
  {
    id: 4,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '- S$ 150',
    amountColor: 'black',
    type: 'Charged to debit card',
    icon: Flights,
  },
  {
    id: 5,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '- S$ 150',
    amountColor: 'black',
    type: 'Charged to debit card',
    icon: FileStorage,
  },
  {
    id: 6,
    merchant: 'Hamleys',
    date: '20 May 2020',
    amount: '- S$ 150',
    amountColor: 'black',
    type: 'Charged to debit card',
    icon: FileStorage,
  },
];
